name: NextDNS to Vercel

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  fetch-process-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Fetch NextDNS logs
        run: |
          curl -X GET 'https://api.nextdns.io/profiles/85d564/logs' \
          -H 'X-Api-Key:f31f2871d328a52a45fefadc09a1c67d0dd5d53d' \
          -o nextdns_logs.json
      
      - name: Process logs and generate HTML
        run: |
          cat << EOF > process_logs.go
          package main
          
          import (
              "encoding/json"
              "html/template"
              "io/ioutil"
              "log"
              "os"
          )
          
          type LogEntry struct {
              Timestamp string \`json:"timestamp"\`
              Domain    string \`json:"domain"\`
              Action    string \`json:"action"\`
          }
          
          type LogsResponse struct {
              Logs []LogEntry \`json:"data"\`
          }
          
          type PageData struct {
              Logs []LogEntry
          }
          
          func main() {
              data, err := ioutil.ReadFile("nextdns_logs.json")
              if err != nil {
                  log.Fatal(err)
              }

              var response LogsResponse
              err = json.Unmarshal(data, &response)
              if err != nil {
                  log.Fatal(err)
              }

              tmpl := template.Must(template.New("logs").Parse(\`
          <!DOCTYPE html>
          <html lang="pt-BR">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Logs do NextDNS</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }
                  h1 { color: #333; }
                  table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                  th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
                  th { background-color: #f2f2f2; color: #333; }
                  tr:nth-child(even) { background-color: #f9f9f9; }
              </style>
          </head>
          <body>
              <h1>Logs do NextDNS</h1>
              <table>
                  <tr>
                      <th>Timestamp</th>
                      <th>Domínio</th>
                      <th>Ação</th>
                  </tr>
                  {{range .Logs}}
                  <tr>
                      <td>{{.Timestamp}}</td>
                      <td>{{.Domain}}</td>
                      <td>{{.Action}}</td>
                  </tr>
                  {{end}}
              </table>
          </body>
          </html>
              \`))

              os.Mkdir("public", 0755)
              f, err := os.Create("public/index.html")
              if err != nil {
                  log.Fatal(err)
              }
              defer f.Close()

              if err := tmpl.Execute(f, PageData{Logs: response.Logs}); err != nil {
                  log.Fatal(err)
              }
          }
          EOF

          go run process_logs.go
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          echo '{
            "version": 2,
            "builds": [
              { "src": "public/**", "use": "@vercel/static" }
            ],
            "routes": [
              { "src": "/(.*)", "dest": "/public/$1" }
            ]
          }' > vercel.json
          vercel deploy --prod --token vGXvCULtXjKWHV4qlIndkyyz --project prj_57YWFOcaIWhMggbcs8ZTv31B4TYX
